### ISSUE TITLE
Meshes of an object are added to the scene with no parent

### ISSUE THREAD

**Issue by Death111** [kaisalmen/WWOBJLoader#1]
Hey,

I load a car (obj+mtl) and it appears in the scene. But each mesh of the car is added to the scene seperatly. So I don't have a parent object with which I can move all meshes of the car. Does not matter if I stream it or not.

Original OBJLoader loader creates a parent mesh, and adds all mesh definitions as children. I see that maybe I would need to have the obj file contain a group?

Thanks
death

**Comment by kaisalmen** [comment]
Use a pivot/dummy object:
```
this.pivot = new THREE.Object3D();
```
and use it as the base node:
```
var objLoader = new THREE.OBJLoader2();
objLoader.setSceneGraphBaseNode( scope.pivot );
```
This should solve your problem. See highlighted lines in [OBJLoader2Example](https://github.com/kaisalmen/WWOBJLoader/blob/master/test/objloader2/OBJLoader2Example.js#L69-L86).

**Comment by Death111** [comment]
I see. I understood that the parameter should always point to the threejs scene ;) But yeah, passing a child of the scene to it will work. Thanks!
