### ISSUE TITLE
Add n-gon support

### ISSUE THREAD

**Issue by kaisalmen** [kaisalmen/WWOBJLoader#12]
`OBJLaoder2` does not support n-gon. Feature should be added.

**Comment by jonnenauha** [comment]
@kaisalmen what source files and functions should people start looking at, if they want to help out on this? Can you give an high level overview what this would involve.

**Comment by kaisalmen** [comment]
Start here: parseArrayBuffer:
https://github.com/kaisalmen/WWOBJLoader/blob/master/src/loaders/OBJLoader2.js#LL258-LL299
processLine:
https://github.com/kaisalmen/WWOBJLoader/blob/master/src/loaders/OBJLoader2.js#LL387-LL429
and from there further down.

This is designed with triangle and quads in mind and processing must be rethought for n-gons.

More to come

**Comment by kaisalmen** [comment]
Adopted solution from three.js #11871. 
Performance is no impacted.
Simplified code.
