### ISSUE TITLE
Loader does not assign names to instances.

### ISSUE THREAD

**Issue by carlosanunes** [kaisalmen/WWOBJLoader#13]
The loader does not assign the names in the .obj file to the corresponding created three.js mesh or group instances.

**Comment by kaisalmen** [comment]
@carlosanunes issue #8 fixed that g (group names) overrule o (object names) when present.
Did you observe this with the latest version and is it possible to provide me an URL of the OBJ file in question?

**Comment by carlosanunes** [comment]
Apologies, tried it again with latest version, it is working.

**Comment by kaisalmen** [comment]
Version 1.2.1 included in three.js release 86 does not yet have this fix. It will be contained in release 87.
