### ISSUE TITLE
WWObjloader2 not applying the textures correctly

### ISSUE THREAD

**Issue by praveendr506** [kaisalmen/WWOBJLoader#14]
only applies the first texture

For Reference : https://stackoverflow.com/questions/45659103/threejs-how-to-load-big-models-without-crashing-the-browser

Library name : OBJLoader2.js Function : RawObject.prototype.finalize(), texture application i guess is failing at this point

**Comment by kaisalmen** [comment]
Hi @praveendr506 
I can confirm this bug and I already found the reason and a solution.
The material was not properly assigned for new RawObjects. I assigned mtllib instead of usemtl. This was wrong. Non-indexed array transformation in finalize is made more robust.
Thanks for spotting this.

**Comment by kaisalmen** [comment]
@praveendr506 I will upload fixed code and bespoke model to a url later tonight for verification...

**Comment by praveendr506** [comment]
Thanks Kaisalmen for the quick fix !!!

**Comment by kaisalmen** [comment]
@praveendr506 check out the fixed version:
https://kaisalmen.de/issues/14/test/issue14/main.src.html
