### ISSUE TITLE
Option to suppress console messages

### ISSUE THREAD

**Issue by Coburn37** [kaisalmen/WWOBJLoader#15]
There should be an option to suppress all console messages (like a quiet mode). Using `THREE.OBJLoader2.WWOBJLoader2.setDebug()` only changes the visibility of more fine grained debug messages.

**Comment by kaisalmen** [comment]
There should probably be a logging wrapper, but I want to introduce a dependencies to some logging library...

**Comment by kaisalmen** [comment]
I have added a `ConsoleLogger`. This warps all console logging calls and can be completely silenced (`setEnabled` function). Debug is now completely handled by it. Removed the functionality from OBJLoader2/Parser. All logging calls that could be disabled (silenced) need to be passed as functions. Then function code is then only executed if `enabled` or `debug` flag is set. `warn` and `error` are excluded from silencing. What do you think?

**Comment by Coburn37** [comment]
This looks great! Thank you so much

Why are they passed as functions though? Is this something that needs to be done because it's a web worker?

**Comment by kaisalmen** [comment]
The idea is if logging is disabled, then the function is not executed. Otherwise a bigger concatenated string might get build and then not logged (see https://github.com/kaisalmen/WWOBJLoader/blob/Issue15/src/loaders/OBJLoader2.js#L777-L791). But, this is making the code more complicated. I have to make up my mind whether this should stay or if I should fall back to just pass strings that are build all the time, but which may just not get logged.
What do you think?

**Comment by Death111** [comment]
I commented all log outputs - So 👍 on this enhancement.
You should just provide a wrapper for console.log
If you look in the docs https://developer.mozilla.org/de/docs/Web/API/Console/log we can use
```
console.log(msg [, subst1, ..., substN]);
// like
console.log("My name is %s", "Nico"); 
```
So if you wrap this function call (msg and optional parameters) and only execute console.log if it is enabled, the problem should be solved. I'm just not sure right now, how I can implement optional parameters.

**Comment by kaisalmen** [comment]
I made the logXYZ calls to use strings again. The usage is just much simpler. Whenever there is a bigger statement helper methods ìsEnabled` and ìsDebug` can be used to prevent construction of a bigger string that is then not logged.

**Comment by Coburn37** [comment]
I like this, simplifies the API and if the big string generation is behind
the debug flag that should be fine. Even if it wasn't it doesn't look like
their being generated in any critical performance part of the application
so you're probably good. Would've commented sooner but my phone crashes
when trying to view changelogs in Chromes browser...
