### ISSUE TITLE
Progress should be returned as/with a numeric

### ISSUE THREAD

**Issue by Coburn37** [kaisalmen/WWOBJLoader#16]
It would be more useful if the progress callback passed a numeric or an object containing a numeric instead of just passing strings.

Currently if to map the progress amount to something like a loading bar, you have to rely on a specific message format and parse the message for the value using `parseFloat()`. Even then, the messages with progress only seem to be emitted for downloading the model, not parsing.

For a starting point, THREE.js loaders already have a progress format which returns an object (emphasis mine):

> onProgress — Will be called while load progresses. The argument will be the XMLHttpRequest instance, which **contains .total and .loaded** bytes.

**Comment by kaisalmen** [comment]
I have changed the number and the behaviour of callbacks and many other things on [dev](https://github.com/kaisalmen/WWOBJLoader/tree/dev) branch, but your request is still valid. Dev branch will hopefully evolve in next version of OBJLoader2 for three.js (three.js #12048). Please take a look, if you are interested.

**Comment by Coburn37** [comment]
Yeah, it seems like it's still passing text strings in the `dev` branch. I suppose updates would need to be made to these call sites (at the least):

* https://github.com/kaisalmen/WWOBJLoader/blob/dev/src/loaders/OBJLoader2.js#L68-L73
* https://github.com/kaisalmen/WWOBJLoader/blob/dev/src/loaders/OBJLoader2.js#L585 (though it doesn't look like the parser has any sort of % complete yet)
* https://github.com/kaisalmen/WWOBJLoader/blob/dev/src/loaders/support/LoaderCommons.js#L279-L297

There's more than this but these seem to be the most important ones. Not sure what I would do with all the messages that don't have any numeric weight to them. Either removing them, changing them to be just debug messages, or possibly including a `.message` property along with a `.loaded` and `.total` might be helpful.

**Comment by kaisalmen** [comment]
I guess it would be a better practice to wrap all arguments passed in each of the callbacks into `CustomEvents`. Yes, for `onProgress` `XMLHttpRequest` is a good template.

**Comment by kaisalmen** [comment]
`onProgress` is now fully addressed, I think. Other callbacks need to be checked.

**Comment by kaisalmen** [comment]
Uih, rebase leaves traces 😄

**Comment by kaisalmen** [comment]
@Coburn37 this is the CustomEvent for progress `numericalValue` is between 0.0 and 1.0 (file download or bytes parsed):
```javascript
var event = new CustomEvent( 'OBJLoader2Event', {
	detail: {
		type: type,
		modelName: this.modelName,
		instanceNo: this.instanceNo,
		text: content,
		numericalValue: value
	}
} );
```
For example mesh loaded progress info log statement looks like this (percentage calculated from `numericalValue` is new:
`Progress: Adding mesh(es) (1: mesh1.002_mesh1-geometry_FrontColorNoCullingID_orig_02_-_Defaul1noCu) from input mesh: mesh1.002_mesh1-geometry_FrontColorNoCullingID_orig_02_-_Defaul1noCu (55.17%)`

**Comment by Coburn37** [comment]
Perhaps a little heavy weight but WWObjLoader2 does happen to handle quite a bit in terms of loading multiple OBJ files, etc... so this will be fine. Thanks!

Now I just need to figure out how to get a combined progress float amount, or possible just split up OBJ loading into two progress categories.

**Comment by kaisalmen** [comment]
> Perhaps a little heavy weight but WWObjLoader2 does happen to handle quite a bit in terms of loading multiple OBJ files, etc... so this will be fine. Thanks!
Yes, I am not sure whether there is really need for `CustomEvent` as I it is not fired or if a simple object would be sufficient. Using an event is more future proof if ever events should be fired...

Yes, `type` gives you an idea what is going on (first 50%) and then parse next (second 50%). Doing this up front in the loader is over-constraining or not good as users might just use `parse` or `parseAsync`.

**Comment by kaisalmen** [comment]
I have decided to use simple js objects that mimic the structure of `CustomEvent`. Advantage: Not so heavy and could be replaced in the future.
