### ISSUE TITLE
When the data is loading, can I terminate it early?

### ISSUE THREAD

**Issue by wdkkk** [kaisalmen/WWOBJLoader#17]
i try to teimanate it when the data is loading by call ` _finalize('complete')`,but  i get an error 
`WWOBJLoader2.js:307 Uncaught DOMException: Failed to execute 'postMessage' on 'Worker': ArrayBuffer at index 0 is already neutered.`
and Can i do that ?

**Comment by wdkkk** [comment]
The error occurred when i try to reload the model  which i have disposed

**Comment by kaisalmen** [comment]
Are you able to share your code? If you disrupt loading by calling `_finalize` you very likely need to reset `OBJLoader2`. Upcoming version (see dev branch) inforces it.

**Comment by wdkkk** [comment]
ok, I have solved this problem . the reason is that i set `THREE.Cache` true ,and when the fileloader try to reload the model from the cache but no data( ??why) ,so the worker will throw an exception because the arraybuffer is empty.
```
var cached = Cache.get( url );

if ( cached !== undefined ) {
     //...
   return cached;
}
```
