### ISSUE TITLE
Don't add objects to the sceneGraph automatically

### ISSUE THREAD

**Issue by Death111** [kaisalmen/WWOBJLoader#2]
I want to control the sceneGraph in my own logic. The loader should not add objects to the sceneGraph on its own.
Maybe I want to move the object, or hide it, before its added to the scene graph. Loader should call me, if the object is finished with a reference to the THREE.Object3d and I can proceed how I like with it.

Basically I would remove the sceneGraphBaseNode parameter from the loader.

**Comment by kaisalmen** [comment]
There is a meshLoaded callback in `WWOBJLoader2`, but it does only allow to override the material.
I may make sense to expand this functionality and also add it to `OBJLoader2`.

**Comment by kaisalmen** [comment]
I have started work on [issue #3](https://github.com/kaisalmen/WWOBJLoader/issues/3) first, but this enhancement will come next on this branch:
https://github.com/kaisalmen/WWOBJLoader/tree/CallbackImprovements

**Comment by kaisalmen** [comment]
b490a7856deb1a78916a0bc14306a3519234ddd9 allows to override material or bufferGeometry or to completely disregard the mesh from `WWOBJLoader2.callbacks.meshLoaded`

**Comment by kaisalmen** [comment]
The requested enhancement is now available: f2df1f7

npm release 1.2.0 of wwobjloader2 including this will follow soon.
