### ISSUE TITLE
The "position" attribute is likely to have NaN values.

### ISSUE THREAD

**Issue by ksabariraj** [kaisalmen/WWOBJLoader#21]
Hi,

Thanks for the plugin.

When I am tried to download the OBJ's, I am getting the below error. Could you please help me on this?

**

> THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values.

**

Thanks,
Sabari.

**Comment by kaisalmen** [comment]
@ksabariraj I have not come across this error, yet. Is the OBJ producing the problem accessible publicly, so I can check? Thanks, Kai

**Comment by ksabariraj** [comment]
Hi Kai,

Thanks for your response.

FYI: I tried the same OBJ with Three.js ObjLoader and its loading successfully.

The below google URL contains the OBJ file.

_https://drive.google.com/open?id=0B8RHl2n48gDWdjhIRHFRR3ZKV3M_

Thanks,
Sabari.

**Comment by ksabariraj** [comment]
Hi Kai,

Thanks for your valuable time and commit. It fixed my issue 👍. I have one more question. What about multi children (Mesh)? for example.

3D Group object (name: Books)

- Mesh1 (name: book1)
- Mesh2 (name: book2)
- Mesh3 (name: book3)
- Mesh4 (name: book4)

The current Web Worker only returns parent Mesh.

Thanks,
Sabari.

**Comment by kaisalmen** [comment]
@ksabariraj thanks for spotting this. It was a real bug. 👍 Once I am sure the fix does not introduce regressions I will merge it. So far it looks good, though.

Regarding your question. 'g' or 'o' declaration in OBJ file should lead to a new mesh if faces definitions follow and if at least vertices where declared before. Does your observation apply only with the new fix or before and is the behaviour different when loading sync and async (worker)? With version 2.x.x+ this should always lead to the same results.
Is it possible to share the file in question as well?

**Comment by ksabariraj** [comment]
Thanks for your comment. My observation apply only with the new fix. Sure I will share the files.

**Comment by ksabariraj** [comment]
Sure, I will check and let you know. Thanks for your time and code :)

**Comment by KiWiGiW** [comment]
![image](https://user-images.githubusercontent.com/30846915/150790285-ba09e151-8081-4b30-8390-2e85f20d13d4.png)
![image](https://user-images.githubusercontent.com/30846915/150790304-ea745a6e-4ef8-476a-b9ef-447fc4d648f5.png)

**Comment by KiWiGiW** [comment]
![image](https://user-images.githubusercontent.com/30846915/150790401-1845775a-e021-453e-97e6-ba6e56f33fd0.png)
