### ISSUE TITLE
Error after build

### ISSUE THREAD

**Issue by ksabariraj** [kaisalmen/WWOBJLoader#22]
Hi Kai,

I am getting the below error after build. Could you please help me on this?

<img width="776" alt="screen shot 2017-10-26 at 11 35 14 pm" src="https://user-images.githubusercontent.com/3765085/32069327-712b137e-baa6-11e7-9fdf-ac230baa43fd.png">
<img width="1173" alt="screen shot 2017-10-26 at 11 35 36 pm" src="https://user-images.githubusercontent.com/3765085/32069334-77a63e68-baa6-11e7-9090-371abbdb381c.png">

Thanks,
Sabari.

**Comment by kaisalmen** [comment]
@ksabariraj I just fixed that. It only happens with the minified version. Please try with latest commit from master branch: https://github.com/kaisalmen/WWOBJLoader/commit/b53c096c24d301c94c66e1ff9bb01ccf94b48570

**Comment by ksabariraj** [comment]
Hi Kai,

Thanks for your commit. It fixed the issue and loading now but getting new error. 

<img width="538" alt="screen shot 2017-10-27 at 8 00 40 am" src="https://user-images.githubusercontent.com/3765085/32085497-099e224a-baed-11e7-9221-15a48555edea.png">

Thanks,
Sabari.

**Comment by kaisalmen** [comment]
Hi Sabari,

I just checked with the latest commit from the master branch: 576899a84417e590dce8287f78b5d67346ddf8f5 It looks fine. I built the project with `gulp` and then checked the minified version for example with test/wwparallels/main.min.html

If you do the same do you still get error?

Cheers,

Kai

**Comment by ksabariraj** [comment]
Yes, I am getting the same error. I am checking on it.

**Comment by kaisalmen** [comment]
What about you commit your code on your fork of this repo? Then I can check...

**Comment by kaisalmen** [comment]
If your loader is not derived from `THREE.LoaderSupport.LoaderBase` and you did not set any callbacks this error can occur. Should be fixe now! 😄

**Comment by kaisalmen** [comment]
A loader implementations must support property `callbacks` now.

**Comment by ksabariraj** [comment]
Thanks.

**Comment by kaisalmen** [comment]
I thought about it again and in the future `WorkerDirector` will enforce this. If conditions are not met loader creation will:
```javascript
if ( ! loader.hasOwnProperty( 'callbacks' ) ) {

	throw classDef.name + ' has no property "callbacks".';

} else if ( ! ( loader.callbacks instanceof THREE.LoaderSupport.Callbacks ) ) {

	throw classDef.name + '.callbacks is not of type "THREE.LoaderSupport.Callbacks".';

}
```

**Comment by ksabariraj** [comment]
Thanks for the code.

**Comment by happytoTom** [comment]
Hi Kai.
When I update to the latest version, there are still errors after compiling. Could you please help me on this? I'm using Webpack.
![image](https://user-images.githubusercontent.com/12823965/35603387-14ef8748-0678-11e8-897f-ccef03836c02.png)

thanks.

**Comment by kaisalmen** [comment]
@happytoTom this seems to be a minification issue (issue #31).
Did you use the latest release (2.2.0) or the latest version from the master branch?

**Comment by happytoTom** [comment]
@kaisalmen Yesterday I updated the code, Objloader2_version is 2.1.0, but this error occurs, where can I get 2.2.0。
thanks.

**Comment by happytoTom** [comment]
@kaisalmen hi Kai i update code for  the master branch, but the code is not working? Do you kownHow to solve this problem？ 
thanks.
![image](https://user-images.githubusercontent.com/12823965/35632355-6ca3c7ce-06e1-11e8-82b5-eca137627593.png)
![image](https://user-images.githubusercontent.com/12823965/35632391-7ea4acc2-06e1-11e8-9aaf-147e207a60fe.png)

**Comment by kaisalmen** [comment]
@happytoTom is your code accessible online (GitHub or some web site)?
Could you please post the Console output from Chrome or better are you able to copy the code of the generated worker Blob (for example Chrome DevTools -> Sources View and here it appears as Blob in the Network View).
Thanks
Btw, version reported on master branch is currently incorrect. I will correct that...
