### ISSUE TITLE
Browser limits download

### ISSUE THREAD

**Issue by ksabariraj** [kaisalmen/WWOBJLoader#23]
Hi Kai,

I am getting one more issue. For example, I have 5 worker, when the objects are downloading the materials were downloaded and started to downloading textures.  In my case, I have 5 to 10 texture for each 3D object. Because of texture started download, browser is limiting the worker download.

Is there any other alternative way to download texture after 3D object downloaded?

Thanks,
Sabari.

**Comment by kaisalmen** [comment]
@ksabariraj, I don't have a good answer, currently. For comparison, did you try to load the OBJ without using the MTLs to see whether the behaviour is really different?

Btw, please share you code. It would really help to understand problems. If that is not possible, please create an example that reproduces the issue.

Thank you

**Comment by ksabariraj** [comment]
@kaisalmen, I will create some example and I share with you. For now, I am trying to load textures from different domain. So, it won't limit the 3D files download. I will try and let you know the status. Thanks again for your time :)

**Comment by kaisalmen** [comment]
Will be re-opened if required.
