### ISSUE TITLE
Not sure about some code typos?

### ISSUE THREAD

**Issue by jimtang** [kaisalmen/WWOBJLoader#29]
Hi, I followed WWOBJLoader from three.js OBJLoader2, and found some code not very sure are they typos or just wrote intentional, please check it:
```
function ResourceDescriptor( url, extension ) {
	var urlParts = url.split( '/' );

	if ( urlParts.length < 2 ) {

		this.path = null;
		this.name = this.name = url; // why set double times?
```

```
this.workerSupport.run(
	{
               ...
	},
	[ content.buffer ] // but WorkerSupport.run only declares 1 parameter, how could this be passed?
);
```

**Comment by kaisalmen** [comment]
Hi @jimtang,

the first one is an error. Fortunately, it does not have any bad effects as the correct value is assigned in the end. Thanks for spotting this.

The call to `Worker.postMessage` supports this, but the wrapping methods do not expose this. I need to think about a better solution here with a clear function signature.

Thanks,

Kai

**Comment by jimtang** [comment]
Ah, I see. Thanks for a quick reply!

**Comment by kaisalmen** [comment]
`this.workerSupport.run()` only requires one parameter. I have corrected `OBJLoader2` The transferable is extracted inside `WorkerSupport` if it exists which means `data.input` of the payload object is an ArrayBuffer.

Thanks for spotting these things! 👍
