### ISSUE TITLE
Each Queue item should have its own callbacks

### ISSUE THREAD

**Issue by Death111** [kaisalmen/WWOBJLoader#3]
Each queue item should have its own callbacks. Like the "fileObj" and "fileMtl" parameters, there should be an onSuccess and onFailure parameter aswell.

This way I can use different handlers for different objects. If I wanted, I could still use the same handler for all of them.

**Comment by kaisalmen** [comment]
The parameters used by `WWOBJLoader2Director.prototype.enqueueForRun` could be extended. If callbacks are defined here, they will be used in addition.
I want to introduced callback arrays in `WWOBJLoader2`. Then, for a specific callback type like `completedLoading` more then one callback can be registered.

**Comment by kaisalmen** [comment]
Check out the enhancement work here: https://github.com/kaisalmen/WWOBJLoader/tree/CallbackImprovements

`WWOBJLoader2` allows multiple callbacks per callback-type and `WWOBJLoader2Director` allows to set callbacks per queued object in addition to global callbacks (if set).

**Comment by kaisalmen** [comment]
The requested enhancement is now available: f2df1f7136b94f4500608c8da512037bdb98b179

See the **WWParallels example** [here](https://github.com/kaisalmen/WWOBJLoader/blob/master/test/wwparallels/WWParallels.js#L151-L153) and [here](https://github.com/kaisalmen/WWOBJLoader/blob/master/test/wwparallels/WWParallels.js#L189-L199).

You are available to register every callback you can globally register for every single obj file when using `WWParallels`:
- progress
- completedLoading
- errorWhileLoading
- materialsLoaded
- meshLoaded

**Comment by Death111** [comment]
Great ;) I wonder why callbacks is a separate parameter? It is added to runParams anyway? Why not just have the single runParams parameter and the user adds the callbacks directly to them?
https://github.com/kaisalmen/WWOBJLoader/blob/master/src/loaders/WWOBJLoader2Director.js#L138-L142

**Comment by kaisalmen** [comment]
You are right. Please take a look at the above commit. I decided to make the `THREE.OBJLoader2.WWOBJLoader2.PrepDataArrayBuffer` and `THREE.OBJLoader2.WWOBJLoader2.PrepDataFile` objects a little clearer (move optional things from constructor to public functions) and introduced `THREE.OBJLoader2.WWOBJLoader2.PrepDataCallbacks` which is used by them. This seems heavy, but I want to make the structure clear to the user.

**Comment by Death111** [comment]
I get confused with all the parameters anyway ;) Now its better yeah. What you think about passing an object as parameter? So it is even more clear what parameters mean and optional params can be passed aswell:
`
var prepData = new THREE.OBJLoader2.WWOBJLoader2.PrepDataArrayBuffer({
		"objName": objDef.name,
		"asArrayBuffer": objDef.objAsArrayBuffer,
		"texturePath": objDef.pathTexture,
		"mtlAsString": objDef.mtlAsString,
		"pivot": this.pivot,
		"streamMeshes": this.streamMeshes,
		"callbacks": callbacks
	});
`
And the PrepDataArrayBuffer constructor can check, what parameters are given and what not. It may need to throw an exception if needed params are unavailable. But I would keep the setter methods, too.

**Comment by kaisalmen** [comment]
Well, the object you describe is exactly what `THREE.OBJLoader2.WWOBJLoader2.PrepDataArrayBuffer` represents in the end. I wanted to provide an explicitly defined object which definition can easily checked by looking at the code or the documentation instead of using an anonymous object (what I initially did).
Exposing the name, obj path+name and material path+name in the constructor is a good compromise, I think.

**Comment by kaisalmen** [comment]
I consider this one now closed after commit to master: 13de8cfed8012cb5d02f651fe6013e83437757ef
