### ISSUE TITLE
Add ES6 modules compatibility

### ISSUE THREAD

**Issue by mweibel** [kaisalmen/WWOBJLoader#35]
Would you be open to a PR adding compatibility for ES6 modules (or commonjs modules at least)? 
Currently it's a bit of a hassle to use this loader without the window global THREE set.

Of course that should be doable in a backwards compatible way :)

**Comment by kaisalmen** [comment]
Yes, I am open to it. ES6 is on the road map at least in my head.

Btw, are you aware of this project: https://github.com/Itee/threejs-full-es6

**Comment by mweibel** [comment]
Cool! I can look into it, though now I've seen #36 and I wonder whether those two would interfere much?

> Btw, are you aware of this project: https://github.com/Itee/threejs-full-es6
No, I wasn't aware. Looks interesting. Though I'm a bit hesitant to use it because it's a fork of a huge library and it looks like that project stripped all license information from the original source? :o

**Comment by kaisalmen** [comment]
> Though I'm a bit hesitant to use it because it's a fork of a huge library and it looks like that project stripped all license information from the original source? :/
I agree, but all dependencies for `LoaderSupport` and `OBJLoader2` are already defined there. So, we could copy paste.

#36 will be a big change again and yes, major ES6 work I see after it is done. But, if you want to apply the things from three-full-es6 for this project, feel free to start a new branch from current master and open a PR.
