### ISSUE TITLE
Textures PNG with alpha channel

### ISSUE THREAD

**Issue by jimver04** [kaisalmen/WWOBJLoader#37]
Hi, 

I 've not managed to load a transparent png. The transparency is loaded as black. I have tried the webgl_loader_obj2.html in three.js v91 but no luck. In the normal webgl_loader_obj.html the transparency is ok with 

```
material.transparent = true;
material.side = THREE.DoubleSide;
```
but the aforementioned parameters are not doing anything in webgl_loader_obj2.html

I am attaching the model files for testing

cube.mtl
```
newmtl cube
Ns 96.078431
Ka 1.000000 1.000000 1.000000
Kd 0.640000 0.640000 0.640000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2
map_Kd cube.png
```

cube.obj
```
# Blender v2.77 (sub 0) OBJ File: 'untitled.blend'
# www.blender.org
mtllib cube.mtl
g Cube
v -0.417097 -1.562497 0.256643
v -0.417097 0.437503 0.256643
v -0.417097 -1.562497 -1.743357
v -0.417097 0.437503 -1.743357
v 1.582903 -1.562497 0.256643
v 1.582903 0.437503 0.256643
v 1.582903 -1.562497 -1.743357
v 1.582903 0.437503 -1.743357
vt 0.3333 0.3333
vt 0.3333 0.0000
vt 0.6667 0.0000
vt 0.6667 0.3333
vt 0.0000 0.6667
vt 0.0000 0.3333
vt 0.3333 0.3333
vt 0.3333 0.6667
vt 0.0000 0.0000
vt 0.3333 0.0000
vt 0.3333 0.3333
vt 0.6667 0.3333
vt 0.6667 0.6667
vt 0.3333 0.6667
vt 1.0000 0.0000
vt 1.0000 0.3333
vt 0.6667 0.3333
vt 0.6667 0.0000
vt 0.0000 0.6667
vt 0.3333 0.6667
vt 0.3333 1.0000
vt 0.0000 1.0000
vn -1.0000 0.0000 0.0000
vn 0.0000 0.0000 -1.0000
vn 1.0000 0.0000 0.0000
vn 0.0000 0.0000 1.0000
vn 0.0000 -1.0000 0.0000
vn 0.0000 1.0000 0.0000
usemtl cube
s off
f 2/1/1 4/2/1 3/3/1 1/4/1
f 4/5/2 8/6/2 7/7/2 3/8/2
f 8/6/3 6/9/3 5/10/3 7/7/3
f 6/11/4 2/12/4 1/13/4 5/14/4
f 1/15/5 3/16/5 7/17/5 5/18/5
f 6/19/6 8/20/6 4/21/6 2/22/6
```

and cube.png

![cube](https://user-images.githubusercontent.com/1898502/38196544-6240077c-368c-11e8-9ad8-5ac87e8240f2.png)

Can you please confirm that it is not loading properly and if there is a remedy ? I lost 5 hours on this thing.

BR,
jimver04

This is the good loading with webgl_loader_obj.html:
![image](https://user-images.githubusercontent.com/1898502/38197225-ed27f086-368f-11e8-94c9-96b5595c1bd8.png)

This is the bad loading with webgl_loader_obj2.html: 
![image](https://user-images.githubusercontent.com/1898502/38197278-188df72a-3690-11e8-8e77-f783adb3c8fa.png)

**Comment by kaisalmen** [comment]
Both use `MTLLoader`, so my first  guess is that it is related to smooth group handling. `OBJLoader2` derives different materials from the original if s is 0 or off.
Try to set `s 1` instead of `s off`  in cube.mtl and see whether the behavior changes. I will investigate fully later...

**Comment by jimver04** [comment]
Thanks for your quick reply. I found it, it wasn't "s off". It was needed to place inside the looper the transparent=true and the side = 2
```
var onLoadMtl = function ( materials ) {
						objLoader.setModelName( modelName );
						
					
						
						materials['cube'].transparent = true;
						materials['cube'].side = 2;
						
						objLoader.setMaterials( materials );
						objLoader.setLogging( true, true );
						
						objLoader.load( 'cube/cube.obj', callbackOnLoad, null, null, null, false );
					};
					objLoader.loadMtl( 'cube/cube.mtl', null, onLoadMtl );
```
