### ISSUE TITLE
Textures with transparent PNG in Webworker

### ISSUE THREAD

**Issue by jimver04** [kaisalmen/WWOBJLoader#38]
I want to test now to load transparent PNG in `webgl_loader_obj2_run_director.html`

replace 

```
var prepData;
var modelPrepDatas = [];
prepData = new THREE.LoaderSupport.PrepData( 'male02' );
prepData.addResource( new THREE.LoaderSupport.ResourceDescriptor( 'models/obj/male02/male02.obj', 'OBJ ') );
prepData.addResource( new THREE.LoaderSupport.ResourceDescriptor( 'models/obj/male02/male02.mtl', 'MTL' ) );
prepData.setLogging( false, false );
modelPrepDatas.push( prepData );
```

with 

```
var prepData;
var modelPrepDatas = [];
prepData = new THREE.LoaderSupport.PrepData( 'cube' );
prepData.addResource( new THREE.LoaderSupport.ResourceDescriptor( 'cube/cube.obj', 'OBJ ') );
prepData.addResource( new THREE.LoaderSupport.ResourceDescriptor( 'cube/cube.mtl', 'MTL' ) );
prepData.setLogging( false, false );
prepData.scale = 100.0;
modelPrepDatas.push( prepData );
```

The texture rendered is not transparent.

I don't know where to place `material.transparent = true`
I have placed it in various positions but without any luck.
Do you have any idea ?
In LoaderSupport.js ?

Thanks,
D.

**Comment by kaisalmen** [comment]
There exists `setCallbackOnLoadMaterials` that you can set as global callback to `WorkerDirector` or per `PrepData. For example, this is how it is done as global instruction for `WorkerLoader`:
```javascript
var callbacks = new THREE.LoaderSupport.Callbacks();
callbacks.setCallbackOnLoad( callbackOnLoad );
callbacks.setCallbackOnLoadMaterials( callbackMaterialsLoaded );
this.workerDirector.prepareWorkers( callbacks, maxQueueSize, maxWebWorkers );
```

**Comment by kaisalmen** [comment]
You get the materials array and are then able to loop and alter before OBJ loading begins.

**Comment by jimver04** [comment]
I tried 

```
var callbackMaterialsLoaded = function ( materials ) {
						console.log("fdfffffffffffffff");
					};
				
					
var callbacks = new THREE.LoaderSupport.Callbacks();
callbacks.setCallbackOnProgress( callbackReportProgress );
callbacks.setCallbackOnLoad( callbackOnLoad );
callbacks.setCallbackOnLoadMaterials( callbackMaterialsLoaded );
callbacks.setCallbackOnMeshAlter( callbackMeshAlter );
```
but no luck, callbackMaterialsLoaded  is not called at all.

Instead I placed "material.transparent = true" inside "callbackMeshAlter"  and it works !

**Comment by kaisalmen** [comment]
Yeah, this works, but it is applied every time instead of globally once.

It works without the Director:
https://github.com/kaisalmen/kaisalmen.de/blob/master/demos/zeroSouth/PTV1.js#L273-L370

I used it to tackle a very similar problem. The windows are made transparent. See here:
https://kaisalmen.de/demos/zeroSouth/PTV1.html

There seems to be a bug in `WorkerDirector` callback assignment when a single loader is configured for run. This needs to be fixed.

**Comment by kaisalmen** [comment]
`onMeshAlter` and `onLoadMaterials` callbacks are now properly handled (return values) by `LoaderWorkerDirector` and fixed `LoadedMeshUserOverride` handling in `LoaderBuilder.js` (meshes were removed due wrong code logic)
