### ISSUE TITLE
AddResource as ArrayBuffer

### ISSUE THREAD

**Issue by jimver04** [kaisalmen/WWOBJLoader#39]
Hi Kai, 

How can I insert the obj as arraybuffer? My obj is not in a url. It is in client side and it is already loaded as text in a dom.

I have tried this: 
```
prepData.addResource( new THREE.LoaderSupport.ResourceDescriptor( '', 'OBJ ').setContent(objDef.objAsArrayBuffer) );
```
but no luck.

It seems that the old good PrepDataArrayBuffer was much better.

Thanks,
D.

**Comment by kaisalmen** [comment]
This should work and I use it elsewhere when unzipping content first (wwobjloader2stage test). What does the console log say. Do you see any errors? 
Content is evaluated here:
https://github.com/kaisalmen/WWOBJLoader/blob/master/src/loaders/support/LoaderCommons.js#L271-L335

Try stepping through `checkResourceDescriptorFiles`

**Comment by jimver04** [comment]
It says  "TypeError: resource is undefined"
in
LoaderSupport.js:286:9
```if ( ! Validator.isValid( resource.name ) ) continue;```

which stems from  OBJLoader2.js:266:19
```var available = prepData.checkResourceDescriptorFiles( prepData.resources,
			[
				{ ext: "obj", type: "ArrayBuffer", ignore: false },
				{ ext: "mtl", type: "String", ignore: false },
				{ ext: "zip", type: "String", ignore: true }
			]
```

**Comment by kaisalmen** [comment]
Just provide a dummy url. The name us derived from the URL. This should do the trick:
```javascript
prepData.addResource( new THREE.LoaderSupport.ResourceDescriptor( 'dummy.obj', 'OBJ ').setContent(objDef.objAsArrayBuffer) );
```

**Comment by jimver04** [comment]
I have managed to load an obj with mtl but without any texture.
In case the texture is also a string loaded in a dom how do I pass it with setContent ?

**Comment by kaisalmen** [comment]
`MTLLoader` tries to load the textures from path provided in the MTL file relative to your HTML or relative to the path set in `OBJLoader2`. If you have ready materials with textures loaded you can set them with the callback.

**Comment by kaisalmen** [comment]
@jimver04 A valid name is now always set in THREE.LoaderSupport.ResourceDescriptor. The check will no longer fail in your case. A valid URL or content must be supplied, though.
