### ISSUE TITLE
Cache obj/mtl for multiple use

### ISSUE THREAD

**Issue by Death111** [kaisalmen/WWOBJLoader#4]
An enhancement would be, that the loader notices, if e.g. the same obj file is requested multiple times. Right now it will load the same file n times. Would be great, if we could specify if the loader should 'cache' the files. If they are requested again, they just return a copy (could be a parameter if you want to clone the mesh, or reuse the one available).
This would save time, as the download and parsing can be spared for files, which were downloaded and parsed in the past already.

**Comment by Coburn37** [comment]
I don't think this library should handle this and it should be something left up to the user to do. Our current application targets a single page web application and I'd rather not have 100MB obj files sitting around in memory if I can help it when the user navigates to a different view.

But that's just my application, it might be more useful for a general audience. I'd be curious if THREE.js did anything like this in their system. I don't think they do.

**Comment by Death111** [comment]
I see what you are saying.
The caching can only be temporarily while executing the queue. So e.g. in the example provided (Web Worker OBJ Parallels Demo) it queues a lot of items, which do load the same mesh over and over (like female02.mtl, female02.obj). It would be sufficient to load it once and then just clone it. I know that this is a bad example, but if I e.g. have a ton of street signs using the same .obj, but differ in the used texture (defined in different .mtl files) it would be sufficient to load the obj once.

**Comment by kaisalmen** [comment]
Hey, I did not receive any notification from GitHub about new issues. I will check my settings. Sorry for not answering, yet.

The purpose of the parallels is to show that interactivity is given while multiples models are continuously loaded by multiple workers. A real application should best use instanced rendering when static objects are used.
