### ISSUE TITLE
Support compressed files

### ISSUE THREAD

**Issue by Death111** [kaisalmen/WWOBJLoader#42]
Hey,

would be great to support zipped obj files. So we could save a lot of bandwidth. Unzipping should then be done in the webworker aswell. What do you think?

Best Regards,
Nico

I found this example: https://discourse.threejs.org/t/obj-mtl-files-from-zip-file/2175 which use JSZip as library https://stuk.github.io/jszip/  Not sure if we can / want another lib as dependency :/

**Comment by kaisalmen** [comment]
Hey @Death111 I would like to keep the dependency list short
Are you aware of this?
https://github.com/kaisalmen/WWOBJLoader/blob/master/test/wwobjloader2stage/WWOBJLoader2Stage.js#L415-L510

These `ZipTools` rely on `jszip` and are used to decompress files before they are parse. An idea is to introduce this as a "on-demand" dependency. Only if these functions are used, then the library is checked to exist.

**Comment by Death111** [comment]
I did not know this! Is there an example on how to use it? If not I will look into it ;)

**Comment by kaisalmen** [comment]
See: https://github.com/kaisalmen/WWOBJLoader/blob/dev/src/loaders/pipeline/utils/ResourceDescriptor.js#L150-L154
