### ISSUE TITLE
Error handling material loader

### ISSUE THREAD

**Issue by twiggler** [kaisalmen/WWOBJLoader#43]
1. [The](https://github.com/kaisalmen/WWOBJLoader/blob/f6aee6cd644bb2716ccc0221fb683bc4c94ad475/src/loaders/OBJLoader2.js#L1397) callback `this._onProgress` does not exist.
1. When called from [here](https://github.com/kaisalmen/WWOBJLoader/blob/f6aee6cd644bb2716ccc0221fb683bc4c94ad475/src/loaders/OBJLoader2.js#L1397), `this` is not bound to  an `OBJLoader2` and thus [the call](https://github.com/kaisalmen/WWOBJLoader/blob/f6aee6cd644bb2716ccc0221fb683bc4c94ad475/src/loaders/OBJLoader2.js#L176) to `this.onProgress(.)` will fail.
1. When using `OBJLoader2` with the `WorkerDirector`, and assuming the above issues are fixed, how can I recover from errors related to the material loader when an exception is thrown [here](https://github.com/kaisalmen/WWOBJLoader/blob/f6aee6cd644bb2716ccc0221fb683bc4c94ad475/src/loaders/OBJLoader2.js#L177)?

**Comment by kaisalmen** [comment]
@twiggler the callbacks need to be called in the proper scope. This is currently wrong.
In the outlined scenario the loading task with the exception will be no longer usable in `WorkerDirector`. I will think about a better approach and come back with a proposal. This abortion is to harsh in the context of `WorkerDirector`.

**Comment by kaisalmen** [comment]
@twiggler scoping errors have been fixed and now `OBJLoader2` allows to register a generic error handler. If this callback is available it will be used instead of a throw. `LoaderWorkerDirector` uses this callback to report a problem, but continue with the next loading task.

It looks good here. Please let me know if this solution is good.
Thanks,
Kai

**Comment by twiggler** [comment]
Hi @kaisalmen,

Thanks you for your work; after glancing over the commits I think it will solve the issue, nice.
I will integrate the fix into our project tomorrow, and will let you know how it works out.

Best,
Roel.

**Comment by twiggler** [comment]
Hi @kaisalmen,

The fix is a substantial improvement over the existing situation. 
Perhaps a further enhancement would be to allow specification of the `generic error handler` for the loader worker director?

**Comment by kaisalmen** [comment]
@twiggler I just implemented what you suggested on branch for the next version. See:
565904d1666ce9a36c6498dbc69f6f76bf453679
I just need to backport it to V2.4.x. Basically, you need to flag if processing the queue on this worker should continue (return true false). Even if you say false, the function could trigger the director queue to continue (all in your hands).
This is how it is "tested" currently in `WWParallels` on V3.0.0-dev (#36):
```javascript
var scopedOnReportError = function ( supportDesc, errorMessage ) {

	console.error( 'workerLoaderDirector reported an error: ' );
	console.error( errorMessage );
	return true;

};
this.workerLoaderDirector = new THREE.WorkerLoader.Director( maxQueueSize, maxWebWorkers )
	.setLogging( this.logging.enabled, this.logging.debug )
	.setCrossOrigin( 'anonymous' )
	.setForceWorkerDataCopy( true )
	.setGlobalCallbacks( null, null, null, null, scopedOnReportError );
```

**Comment by twiggler** [comment]
@kaisalmen Looks great; porting this to  2.4 would seal the deal!. 
:thumbsup

**Comment by kaisalmen** [comment]
Done! I think this is now resolved. If you see any problem, please let me know.
