### ISSUE TITLE
Abort request

### ISSUE THREAD

**Issue by twiggler** [kaisalmen/WWOBJLoader#44]
When the user navigates away from the current page, or selects another scene, I want `WorkerDirector.tearDown` to abort xhr requests which have already started.

**Comment by kaisalmen** [comment]
A fair request. I have to investigate if `THREE.FileLoader` supports an abort already or whether something needs to be done in addition. This could in the end be an enhancement issue for three.js, but let's find out first...

**Comment by twiggler** [comment]
Unfortunately, `THREE.FileLoader` also does not support aborting.

Can I help out in some way with either https://github.com/kaisalmen/WWOBJLoader/issues/43 or this issue?

**Comment by kaisalmen** [comment]
I will try to fix #43 in the upcoming week. I think it is easier to find a good solution there.
Here, I have not come up with a good idea, yet.

**Comment by kaisalmen** [comment]
4.0.0 (final release very soon https://www.npmjs.com/package/wwobjloader2/v/4.0.0-rc.0) uses `WorkerTaskManager` which is completely new. Therefore this is closed.
