### ISSUE TITLE
Incorrect indexPointerC initialization.

### ISSUE THREAD

**Issue by youyi1996** [kaisalmen/WWOBJLoader#47]
`indexPointerV` has already be increased twice before, at L1067 and L1068.
https://github.com/kaisalmen/WWOBJLoader/blob/73f4169c2543e831c36269f89b56373961b62036/src/loaders/OBJLoader2.js#L1065-L1080

So actually after this initialization,  `indexPointerC` points to the next vertex's color, which is incorrect.

I suppose the following should be correct .
```Javascript
var indexPointerV = 3 * ( faceIndexVi > 0 ? faceIndexVi - 1 : faceIndexVi + scope.vertices.length / 3 );
var indexPointerC = scope.colors.length > 0 ? indexPointerV : null;

var vertices = scope.rawMesh.subGroupInUse.vertices;
vertices.push( scope.vertices[ indexPointerV++ ] );
vertices.push( scope.vertices[ indexPointerV++ ] );
vertices.push( scope.vertices[ indexPointerV ] );

if ( indexPointerC !== null ) {

    var colors = scope.rawMesh.subGroupInUse.colors;
    colors.push( scope.colors[ indexPointerC++ ] );
    colors.push( scope.colors[ indexPointerC++ ] );
    colors.push( scope.colors[ indexPointerC ] );

}
```

**Comment by kaisalmen** [comment]
This is correct. Thank you for spotting this error. I have already merged a fix to the master branch.
