### ISSUE TITLE
Could worker support be used in other model loaders?

### ISSUE THREAD

**Issue by HypnosNova** [kaisalmen/WWOBJLoader#48]
I want to rewrite Three.js other model loaders and support webworkers. I want to know whether the LoaderWorkerSupport.js could be used in other format loader or it contains methods that only support obj format.

**Comment by kaisalmen** [comment]
I am actually working on this. See here:
https://github.com/mrdoob/three.js/issues/13664

and here:
https://github.com/kaisalmen/WWOBJLoader/tree/dev

**Comment by kaisalmen** [comment]
This will become available once `WorkerTaskManager` is finished.

**Comment by kaisalmen** [comment]
See https://github.com/kaisalmen/three-wtm
