### ISSUE TITLE
Provide NPM package

### ISSUE THREAD

**Issue by kaisalmen** [kaisalmen/WWOBJLoader#54]
`OBJLoader2` and `OBJLoader2Parallel` were removed from three.js in release 125.

I need to provide an npm package (4.0.0) that provides the removed loaders again.

Required tasks:
- [x] Provide "npm" package from dev branch
- [x] Update README and CHANGELOG
- [x] With 4.0.0 release stable branch will be aligned with dev branch

Obsolete tasks as new npm package will only be release from 4.0.0 onward
_- [ ] Provide npm package from release branch_
_- [ ] Update README on release branch_

**Comment by daydream05** [comment]
Yes please! Thank you for your work btw. Just found out they remove this from the three js package. This is the only way I could load .OBJ files bigger than 100 Mb

**Comment by kaisalmen** [comment]
Yes, I will get to it soon.

**Comment by kaisalmen** [comment]
I started to work on it here (WIP snowpack + bundle workflow): 
https://github.com/kaisalmen/WWOBJLoader/tree/npm_package_v4

**Comment by kaisalmen** [comment]
First version is here:
https://www.npmjs.com/package/wwobjloader2/v/4.0.0-beta.0

**Comment by geoff-harper** [comment]
How stable would you say the beta version is?

**Comment by kaisalmen** [comment]
I just release 4.0.0-rc.0. I think it is pretty close to final release now. Need to update the README & CHANGELOG before. Creating workers from uglified code should be more stable now. I fixed multiple issue here and in the WorkerTaskManager repository ( https://github.com/kaisalmen/three-wtm)

I just added the missing types to `package.json`. If this does not work, then please tell me.

I set three.js 0.129.0 as peerDependency now as three-wtm and OBJLoader2 are incompatible with 0.128.0 due to a bug that was fixed with r129. R127 is also possible, but R128 changed three.js substantially, so R129 is the way to go.

**Comment by kaisalmen** [comment]
Thanks for your input regarding types and peerDependencies 👍

**Comment by kaisalmen** [comment]
V4.0.0 is available: https://www.npmjs.com/package/wwobjloader2

**Comment by kaisalmen** [comment]
Hi @submagr version 2.1.2 is tool old (year 2017). It was not modularized at that time. You have to use version 4.0.0 if you want to use wwobjloader2 as independent npm package. Version 3.x.x was only available with three.js directly.
