### ISSUE TITLE
webpackMissingModule for three-wtm

### ISSUE THREAD

**Issue by geoff-harper** [kaisalmen/WWOBJLoader#59]
Webpack is telling me that I'm missing a module and it appears that OBJLoader2 is trying to import this. What is it? If it's a dep is there a reason it isn't in the package file? Do I need to bring it into my project myself?

**Comment by kaisalmen** [comment]
Hi @geoff-harper `three-wtm` **(https://github.com/kaisalmen/three-wtm)** is a peer-dependency. I moved all worker related code to this project with releae 4.0.0.

**Comment by kaisalmen** [comment]
@geoff-harper I consider this resolved. If you experience any further issue once 5.0.0, please report a new issue. Thanks.
