### ISSUE TITLE
OBJLoader2 contains the correct vertices of my obj, but in the scene extra vertices are added to my object

### ISSUE THREAD

**Issue by Dimitris-krm** [kaisalmen/WWOBJLoader#61]
Hello I've been using this repo for my project for indexed geometry and when I load .obj files extra vertices are added to my object 
for example 1 of the objects I use has 750 vertices, OBJloader2.parser.vertices displays them correctly however in OBJloader2.parser.globalCounts it says I have 1510 vertices ? (1 thing I noticed in this specific obj the vt in my file are 1510) 

In my second object I have 90481 vertices and in the globalCount 95172 vertices appear, later on BufferGeometry displays the same 95172 vertices

Am I doing something wrong? Am I not using OBJLoader2 properly? Are there conflicts with three js?

Here's how I load my obj

       var loader= new OBJLoader2(); 
       	loader.setUseIndices(true)
	var textureLoader = new THREE.TextureLoader(loadingManager);
	var map = textureLoader.load('Castle.jpg');	
	var material = new THREE.MeshPhysicalMaterial({map: map, vertexColors: true});
	loader.load( 'Castle.obj', function ( obj ) {		
		obj.traverse( function ( node ) {
	
			if ( node.isMesh ) 
			{
			node.material = material;
			
			}

		  } );

		scene.add(obj)
	} 
	);
	
Thank you for your time and work

**Comment by kaisalmen** [comment]
Hi @Dimitris-krm I haven't investigated this, yet. Are you able/allowed to share the OBJ in question? Thanks, Kai

**Comment by kaisalmen** [comment]
No further feedback
