### ISSUE TITLE
Is it possible to load GLTF file in web-worker?

### ISSUE THREAD

**Issue by samchon** [kaisalmen/WWOBJLoader#67]
Tried below code, but image files are not loaded yet.

Have I understood this library exactly? Or mis-understanding something?

```typescript
import { GLTF, GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { OBJLoader2 } from "wwobjloader2";

export namespace ThreeLoader {
    export function gltf(url: string): Promise<GLTF> {
        const loader: GLTFLoader = new GLTFLoader();
        loader.setDRACOLoader(new OBJLoader2() as any);

        return new Promise((resolve, reject) => {
            loader.load(url, resolve, () => {}, reject);
        });
    }
}
```

**Comment by kaisalmen** [comment]
@samchon sorry, I forgot to answer you.

`OBJLoader2` can only be used as loader for the OBJ file format. It cannot be combined with `GLTFLoader` from three.js.

Three.js `GLTFLoader` can use the DracoLoader internally to load meshes compressed with the Draco. For more explanation, take a look at the three.js docs:
https://threejs.org/docs/#examples/en/loaders/GLTFLoader
