### ISSUE TITLE
Explore aligning types with the core loaders

### ISSUE THREAD

**Issue by geoff-harper** [kaisalmen/WWOBJLoader#68]
I'm back again and was hoping to bring up the discussion of aligning this loader with the core loaders from three. My use case is actually a react app running @react-three/fiber and @react-three/drei. Fiber exports a convenience hook called [useLoader](https://docs.pmnd.rs/react-three-fiber/api/hooks#useloader). It reduces a bit of code but more importantly it caches the result under a key matching the input url. Using the `TextureLoader` as an example (a common pair I'd imagine), we can see the interface:

```tsx
export class TextureLoader {
    constructor(manager?: LoadingManager);

    crossOrigin: string;

    withCredentials: boolean;

    path: string;

    resourcePath: string;
    manager: LoadingManager;

    requestHeader: { [header: string]: string };

    load(
        url: string,
        onLoad?: (texture: Texture) => void,
        onProgress?: (event: ProgressEvent) => void,
        onError?: (event: ErrorEvent) => void,
    ): Texture;

    loadAsync(url: string, onProgress?: (event: ProgressEvent) => void): Promise<Texture>;

    setCrossOrigin(crossOrigin: string): this;
    setWithCredentials(value: boolean): this;
    setPath(path: string): this;
    setResourcePath(resourcePath: string): this;
    setRequestHeader(requestHeader: { [header: string]: string }): this;
}
```

If you ignore the type errors that are thrown, it's already functioning with `useLoader`. As far as types go, it has a lot of crossover already, with the missing properties being a bit of renaming and pretty trivial network stuff from the looks of it. From my perspective it'd be a pretty easy win and would create a happy path for what I imagine a non-insignificant number of people implementing in react. Let me know what you think and if it'd be a good thing to sneak into the upcoming breaking changes

**Comment by kaisalmen** [comment]
@geoff-harper alignment makes sense, I agree. `OBJLoader2` already extends `Loader` from three, but I didn't check for a while if there are alignment/type problems. This should be corrected and aligned before 5.0.0 is released.
Would you like to contribute something?

**Comment by geoff-harper** [comment]
If it's simply adjusting types and adding some network stuff I can take a swing and open a PR. I later noticed that I also wasn't getting an index attribute for some reason when using the `useLoader` hook, but it's fine if I do it more manually. I need to investigate that a bit more but I might need some direction since I'd imagine it's a more underlying issue

**Comment by kaisalmen** [comment]
@geoff-harper does it make sense to add a simple react example directly in this repo? Could you contribute this? Then I could take care of the `Loader` stuff.
Btw, I have just finished overhauling the examples, because I wanted to be able to verify everything works when they are statically served and not only via the vite dev server.

**Comment by geoff-harper** [comment]
Yeah I can do that. If it's a React example then I'll use [@react/three-fiber](https://github.com/pmndrs/react-three-fiber) since it's quickly become the standard wrapper for using the two together

**Comment by kaisalmen** [comment]
`loadAsync` is now working. I added it to the options example.

**Comment by geoff-harper** [comment]
It all looks great, thanks again for all the work you've put in. Im looking forward to giving 5.0.0 a go
