### ISSUE TITLE
Not all example obj files available

### ISSUE THREAD

**Issue by Death111** [kaisalmen/WWOBJLoader#7]
Hey, 

when I tried to get your examples running locally, I did not find the following objects which are referenced in the parralels demo (https://github.com/kaisalmen/WWOBJLoader/blob/master/test/wwparallels/WWParallels.js#L174-L182):
			fileObj: 'vr_controller_vive_1_5.obj',
			fileObj: 'Cerberus.obj',
You mentioned to download them somewhere, but there these two are not available ;) Just wanted to let you know.

Regards
Death

**Comment by kaisalmen** [comment]
You find them here:
https://github.com/mrdoob/three.js/blob/dev/examples/models/obj/cerberus/Cerberus.obj
https://github.com/mrdoob/three.js/blob/dev/examples/models/obj/vive-controller/vr_controller_vive_1_5.obj

They are contained in three.js repo (info is close to the of the README.md: "Just download them from the WWOBJLoader GitHub repository or three.js GitHub repository.").
I did not want to duplicate all models here, especially the big ones.

**Comment by Death111** [comment]
Hm not sure how to get there :)
Following the link in readme I found then this folder, which does not contain the objs ´ .
https://github.com/mrdoob/three.js/tree/dev/examples/obj

**Comment by kaisalmen** [comment]
The `README.md` now contains direct links: 6b948e78bb2226cc797e9575a71d09d598a006d4
😄
