### ISSUE TITLE
Typescript issue with 5.0.0

### ISSUE THREAD

**Issue by gloriousjob** [kaisalmen/WWOBJLoader#71]
When I compile my project with Angular using v5.0.0, I get this error:
```
Error: node_modules/wwobjloader2/dist/OBJLoader2.d.ts:49:20 - error TS2552: Cannot find name 'arraybuffer'. Did you mean 'ArrayBuffer'?

49     parse(content: arraybuffer | string): Object3D;
                      ~~~~~~~~~~~

  node_modules/typescript/lib/lib.es5.d.ts:1677:13
    1677 declare var ArrayBuffer: ArrayBufferConstructor;
                     ~~~~~~~~~~~
    'ArrayBuffer' is declared here.


Error: node_modules/wwobjloader2/dist/OBJLoader2Parser.d.ts:98:29 - error TS2304: Cannot find name 'Mesh'.

98     _onAssetAvailable(mesh: Mesh, materialMetaInfo: object): void;
                               ~~~~
```

It looks like there's a casing error on the first and that it needs an import from three in the second. For now, I'm sticking with v4.0.1, which does not have this error.

**Comment by kaisalmen** [comment]
Hi @gloriousjob thank you for reporting this. That is an error that sneaked after 4.0.1. The TypeScript definitions are generated and take jsdoc definitions into account and these are not correct here. The old definitions contained `ArrayBuffer`. I need to check if there are other errors and will correct those as well.

**Comment by kaisalmen** [comment]
It will take a bit longer, but I decided to finally convert the loader code to TypeScript. See [ts branch](https://github.com/kaisalmen/WWOBJLoader/tree/ts)

**Comment by gloriousjob** [comment]
I like this. Typescript does introduce its own headaches but I've seen it save me from worse headaches that I couldn't figure out in JS.

**Comment by kaisalmen** [comment]
@gloriousjob I completed the TypesScript conversion and merge the ts branch back to main.
You find the npm preview package here:
https://www.npmjs.com/package/wwobjloader2/v/5.1.0-next.2

**Comment by gloriousjob** [comment]
I'm not sure what the problem is but I'm getting this error:
Argument of type 'MaterialCreator' is not assignable to parameter of type 'MaterialCreatorPartialType'.
  Type 'MaterialCreator' is not assignable to type 'AssociatedArrayType<unknown>'.
    Index signature for type 'string' is missing in type 'MaterialCreator'.

The code I'm trying is:
const parsedMtl = new MTLLoader().parse(mtlData, path);
const materials = MtlObjBridge.addMaterialsFromMtlLoader(parsedMtl);
                                                                                                       ^^^^^^^^

**Comment by kaisalmen** [comment]
Sorry, my fault. I broke the signature of `addMaterialsFromMtlLoader`. It is working again:
https://www.npmjs.com/package/wwobjloader2/v/5.1.0-next.3

**Comment by gloriousjob** [comment]
Thanks, it's finally compiling!

**Comment by kaisalmen** [comment]
I need to ensure by review / diff checking, I did not introduce other unwanted API changes and will then release the new version, but I don't if I can make it this week.
